# Generated by Django 6.1 on 2026-08-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='district',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Comilla', 'Comilla'), ("Cox's Bazar", "Cox's Bazar")], default='Dhaka', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='hospital',
            field=models.CharField(default='Square Hospital, Dhaka', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='qualification',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='rating',
            field=models.FloatField(default=4.9),
        ),
    ]
