# Generated by Django 6.1 on 2026-08-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctorprofile_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='district',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh'), ('Comilla', 'Comilla'), ("Cox's Bazar", "Cox's Bazar"), ('Jashore', 'Jashore')], default='Dhaka', max_length=50),
        ),
    ]
